In [2]:
import json
from pathlib import Path
import pandas as pd

In [3]:
BASE_DIR = Path().resolve().parent
RAW_DATA_DIR = BASE_DIR / "data" / "raw"

In [4]:
json_files = list(RAW_DATA_DIR.glob("*.json"))
latest_file = max(json_files, key=lambda file: file.stat().st_mtime)

In [5]:
with open(latest_file, "r", encoding="utf-8") as f:
    data = json.load(f)

In [6]:
type(data)

list

In [7]:
len(data)

50

In [8]:
data[0]

{'id': 'bitcoin',
 'symbol': 'btc',
 'name': 'Bitcoin',
 'image': 'https://coin-images.coingecko.com/coins/images/1/large/bitcoin.png?1696501400',
 'current_price': 68309,
 'market_cap': 1366164565163,
 'market_cap_rank': 1,
 'fully_diluted_valuation': 1366164565163,
 'total_volume': 53394495490,
 'high_24h': 69136,
 'low_24h': 67395,
 'price_change_24h': 913.79,
 'price_change_percentage_24h': 1.35587,
 'market_cap_change_24h': 13292653701,
 'market_cap_change_percentage_24h': 0.98255,
 'circulating_supply': 20010118.0,
 'total_supply': 20010118.0,
 'max_supply': 21000000.0,
 'ath': 126080,
 'ath_change_percentage': -45.82098,
 'ath_date': '2025-10-06T18:57:42.558Z',
 'atl': 67.81,
 'atl_change_percentage': 100637.14427,
 'atl_date': '2013-07-06T00:00:00.000Z',
 'roi': None,
 'last_updated': '2026-04-01T17:55:51.351Z'}

In [9]:
df = pd.DataFrame(data)
df.head()

,id,symbol,name,image,current_price,market_cap,market_cap_rank,fully_diluted_valuation,total_volume,high_24h,...,total_supply,max_supply,ath,ath_change_percentage,ath_date,atl,atl_change_percentage,atl_date,roi,last_updated
0,bitcoin,btc,Bitcoin,https://coin-images.coingecko.com/coins/images...,68309.000000,1366164565163,1,1366164565163,5.339450e+10,69136.000000,...,2.001012e+07,2.100000e+07,126080.00,-45.82098,2025-10-06T18:57:42.558Z,67.810000,1.006371e+05,2013-07-06T00:00:00.000Z,None,2026-04-01T17:55:51.351Z
1,ethereum,eth,Ethereum,https://coin-images.coingecko.com/coins/images...,2137.480000,257759816393,2,257759816393,1.782284e+10,2161.500000,...,1.206914e+08,NaN,4946.05,-56.78413,2025-08-24T19:21:03.333Z,0.432979,4.935679e+05,2015-10-20T00:00:00.000Z,"{'times': 40.83228263073198, 'currency': 'btc'...",2026-04-01T17:55:54.854Z
2,tether,usdt,Tether,https://coin-images.coingecko.com/coins/images...,0.999746,184178313755,3,189643933595,8.052174e+10,0.999841,...,1.896897e+11,NaN,1.32,-24.43392,2018-07-24T00:00:00.000Z,0.572521,7.463312e+01,2015-03-02T00:00:00.000Z,None,2026-04-01T17:54:59.513Z
3,binancecoin,bnb,BNB,https://coin-images.coingecko.com/coins/images...,614.240000,83729663633,4,83729663633,1.053375e+09,620.320000,...,1.363570e+08,2.000000e+08,1369.99,-55.16487,2025-10-13T08:41:24.131Z,0.039818,1.542525e+06,2017-10-19T00:00:00.000Z,None,2026-04-01T17:55:51.210Z
4,ripple,xrp,XRP,https://coin-images.coingecko.com/coins/images...,1.350000,83046183676,5,135222830064,1.958636e+09,1.360000,...,9.998569e+10,1.000000e+11,3.65,-62.92503,2025-07-18T03:40:53.808Z,0.002686,5.022724e+04,2014-05-22T00:00:00.000Z,None,2026-04-01T17:54:59.273Z

In [11]:
df.shape

(50, 26)

In [12]:
df.columns

Index(['id', 'symbol', 'name', 'image', 'current_price', 'market_cap',
       'market_cap_rank', 'fully_diluted_valuation', 'total_volume',
       'high_24h', 'low_24h', 'price_change_24h',
       'price_change_percentage_24h', 'market_cap_change_24h',
       'market_cap_change_percentage_24h', 'circulating_supply',
       'total_supply', 'max_supply', 'ath', 'ath_change_percentage',
       'ath_date', 'atl', 'atl_change_percentage', 'atl_date', 'roi',
       'last_updated'],
      dtype='object')

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 26 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   id                                50 non-null     object
 1   symbol                            50 non-null     object
 2   name                              50 non-null     object
 3   image                             50 non-null     object
 4   current_price                     50 non-null     float64
 5   market_cap                        50 non-null     int64
 6   market_cap_rank                   50 non-null     int64
 7   fully_diluted_valuation           50 non-null     int64
 8   total_volume                      50 non-null     float64
 9   high_24h                          50 non-null     float64
 10  low_24h                           50 non-null     float64
 11  price_change_24h                  50 non-null     float64
 12  price_change_percentage_24h       50 non-null     float64
 13  market_cap_change_24h             50 non-null     float64
 14  market_cap_change_percentage_24h  50 non-null     float64
 15  circulating_supply                50 non-null     float64
 16  total_supply                      50 non-null     float64
 17  max_supply                        26 non-null     float64
 18  ath                               50 non-null     float64
 19  ath_change_percentage             50 non-null     float64
 20  ath_date                          50 non-null     object
 21  atl                               50 non-null     float64
 22  atl_change_percentage             50 non-null     float64
 23  atl_date                          50 non-null     object
 24  roi                               2 non-null      object
 25  last_updated                      50 non-null     object
dtypes: float64(15), int64(3), object(8)
memory usage: 10.3+ KB

In [14]:
selected_columns = [
    "id",
    "symbol",
    "name",
    "current_price",
    "market_cap",
    "market_cap_rank",
    "total_volume",
    "high_24h",
    "low_24h",
    "price_change_24h",
    "price_change_percentage_24h",
    "circulating_supply",
    "total_supply",
    "ath",
    "atl",
    "last_updated"
]

df = df[selected_columns]
df.head()

,id,symbol,name,current_price,market_cap,market_cap_rank,total_volume,high_24h,low_24h,price_change_24h,price_change_percentage_24h,circulating_supply,total_supply,ath,atl,last_updated
0,bitcoin,btc,Bitcoin,68309.000000,1366164565163,1,5.339450e+10,69136.000000,67395.000000,913.790000,1.35587,2.001012e+07,2.001012e+07,126080.00,67.810000,2026-04-01T17:55:51.351Z
1,ethereum,eth,Ethereum,2137.480000,257759816393,2,1.782284e+10,2161.500000,2083.950000,46.900000,2.24337,1.206914e+08,1.206914e+08,4946.05,0.432979,2026-04-01T17:55:54.854Z
2,tether,usdt,Tether,0.999746,184178313755,3,8.052174e+10,0.999841,0.999009,0.000676,0.06771,1.842228e+11,1.896897e+11,1.32,0.572521,2026-04-01T17:54:59.513Z
3,binancecoin,bnb,BNB,614.240000,83729663633,4,1.053375e+09,620.320000,610.050000,0.676841,0.11031,1.363570e+08,1.363570e+08,1369.99,0.039818,2026-04-01T17:55:51.210Z
4,ripple,xrp,XRP,1.350000,83046183676,5,1.958636e+09,1.360000,1.330000,0.022342,1.68044,6.140553e+10,9.998569e+10,3.65,0.002686,2026-04-01T17:54:59.273Z

In [15]:
df["last_updated"] = pd.to_datetime(df["last_updated"], errors="coerce")

In [16]:
numeric_columns = [
    "current_price",
    "market_cap",
    "market_cap_rank",
    "total_volume",
    "high_24h",
    "low_24h",
    "price_change_24h",
    "price_change_percentage_24h",
    "circulating_supply",
    "total_supply",
    "ath",
    "atl"
]

for col in numeric_columns:
    df[col] = pd.to_numeric(df[col], errors="coerce")

In [19]:
df.head()

,id,symbol,name,current_price,market_cap,market_cap_rank,total_volume,high_24h,low_24h,price_change_24h,price_change_percentage_24h,circulating_supply,total_supply,ath,atl,last_updated
0,bitcoin,btc,Bitcoin,68309.000000,1366164565163,1,5.339450e+10,69136.000000,67395.000000,913.790000,1.35587,2.001012e+07,2.001012e+07,126080.00,67.810000,2026-04-01 17:55:51.351000+00:00
1,ethereum,eth,Ethereum,2137.480000,257759816393,2,1.782284e+10,2161.500000,2083.950000,46.900000,2.24337,1.206914e+08,1.206914e+08,4946.05,0.432979,2026-04-01 17:55:54.854000+00:00
2,tether,usdt,Tether,0.999746,184178313755,3,8.052174e+10,0.999841,0.999009,0.000676,0.06771,1.842228e+11,1.896897e+11,1.32,0.572521,2026-04-01 17:54:59.513000+00:00
3,binancecoin,bnb,BNB,614.240000,83729663633,4,1.053375e+09,620.320000,610.050000,0.676841,0.11031,1.363570e+08,1.363570e+08,1369.99,0.039818,2026-04-01 17:55:51.210000+00:00
4,ripple,xrp,XRP,1.350000,83046183676,5,1.958636e+09,1.360000,1.330000,0.022342,1.68044,6.140553e+10,9.998569e+10,3.65,0.002686,2026-04-01 17:54:59.273000+00:00

In [20]:
df["price_range_24h"] = df["high_24h"] - df["low_24h"]

In [21]:
df.head()

,id,symbol,name,current_price,market_cap,market_cap_rank,total_volume,high_24h,low_24h,price_change_24h,price_change_percentage_24h,circulating_supply,total_supply,ath,atl,last_updated,price_range_24h
0,bitcoin,btc,Bitcoin,68309.000000,1366164565163,1,5.339450e+10,69136.000000,67395.000000,913.790000,1.35587,2.001012e+07,2.001012e+07,126080.00,67.810000,2026-04-01 17:55:51.351000+00:00,1741.000000
1,ethereum,eth,Ethereum,2137.480000,257759816393,2,1.782284e+10,2161.500000,2083.950000,46.900000,2.24337,1.206914e+08,1.206914e+08,4946.05,0.432979,2026-04-01 17:55:54.854000+00:00,77.550000
2,tether,usdt,Tether,0.999746,184178313755,3,8.052174e+10,0.999841,0.999009,0.000676,0.06771,1.842228e+11,1.896897e+11,1.32,0.572521,2026-04-01 17:54:59.513000+00:00,0.000832
3,binancecoin,bnb,BNB,614.240000,83729663633,4,1.053375e+09,620.320000,610.050000,0.676841,0.11031,1.363570e+08,1.363570e+08,1369.99,0.039818,2026-04-01 17:55:51.210000+00:00,10.270000
4,ripple,xrp,XRP,1.350000,83046183676,5,1.958636e+09,1.360000,1.330000,0.022342,1.68044,6.140553e+10,9.998569e+10,3.65,0.002686,2026-04-01 17:54:59.273000+00:00,0.030000

In [22]:
def categorize_market_cap(market_cap):
    if pd.isna(market_cap):
        return "unknown"
    elif market_cap >= 10_000_000_000:
        return "large"
    elif market_cap >= 1_000_000_000:
        return "medium"
    else:
        return "small"

df["market_cap_category"] = df["market_cap"].apply(categorize_market_cap)

In [23]:
df["snapshot_date"] = pd.Timestamp.now().date()

In [24]:
df.head()

,id,symbol,name,current_price,market_cap,market_cap_rank,total_volume,high_24h,low_24h,price_change_24h,price_change_percentage_24h,circulating_supply,total_supply,ath,atl,last_updated,price_range_24h,market_cap_category,snapshot_date
0,bitcoin,btc,Bitcoin,68309.000000,1366164565163,1,5.339450e+10,69136.000000,67395.000000,913.790000,1.35587,2.001012e+07,2.001012e+07,126080.00,67.810000,2026-04-01 17:55:51.351000+00:00,1741.000000,large,2026-04-01
1,ethereum,eth,Ethereum,2137.480000,257759816393,2,1.782284e+10,2161.500000,2083.950000,46.900000,2.24337,1.206914e+08,1.206914e+08,4946.05,0.432979,2026-04-01 17:55:54.854000+00:00,77.550000,large,2026-04-01
2,tether,usdt,Tether,0.999746,184178313755,3,8.052174e+10,0.999841,0.999009,0.000676,0.06771,1.842228e+11,1.896897e+11,1.32,0.572521,2026-04-01 17:54:59.513000+00:00,0.000832,large,2026-04-01
3,binancecoin,bnb,BNB,614.240000,83729663633,4,1.053375e+09,620.320000,610.050000,0.676841,0.11031,1.363570e+08,1.363570e+08,1369.99,0.039818,2026-04-01 17:55:51.210000+00:00,10.270000,large,2026-04-01
4,ripple,xrp,XRP,1.350000,83046183676,5,1.958636e+09,1.360000,1.330000,0.022342,1.68044,6.140553e+10,9.998569e+10,3.65,0.002686,2026-04-01 17:54:59.273000+00:00,0.030000,large,2026-04-01

In [25]:
df.describe()

,current_price,market_cap,market_cap_rank,total_volume,high_24h,low_24h,price_change_24h,price_change_percentage_24h,circulating_supply,total_supply,ath,atl,price_range_24h
count,50.000000,5.000000e+01,50.00000,5.000000e+01,50.000000,50.000000,50.000000,50.000000,5.000000e+01,5.000000e+01,50.000000,5.000000e+01,50.000000
mean,1646.027905,4.671271e+10,25.50000,3.610575e+09,1664.452833,1621.083470,24.006107,1.270189,3.014314e+13,3.016632e+13,3069.311204,6.133485e+01,43.369363
std,9669.373805,1.959969e+11,14.57738,1.369596e+10,9785.778922,9539.337229,130.532044,1.969118,1.526508e+14,1.526664e+14,17808.174408,2.813563e+02,246.486650
min,0.000002,1.568221e+09,1.00000,0.000000e+00,0.000002,0.000002,-15.813440,-3.502530,5.141288e+05,5.141288e+05,0.000004,5.636600e-11,0.000000
25%,0.404855,2.668346e+09,13.25000,4.205053e+07,0.407863,0.400820,0.000194,0.038408,2.867320e+08,4.907335e+08,1.022000,5.035201e-02,0.002571
50%,1.000000,4.130936e+09,25.50000,1.407075e+08,1.008000,0.999752,0.003641,1.222180,2.465597e+09,4.411332e+09,2.910000,5.459425e-01,0.018719
75%,48.315000,9.219333e+09,37.75000,4.160963e+08,49.322500,47.877500,0.216084,2.452385,3.198182e+10,4.330007e+10,124.747500,1.019500e+00,1.250000
max,68309.000000,1.366165e+12,50.00000,8.052174e+10,69136.000000,67395.000000,913.790000,6.937400,9.165331e+14,9.165331e+14,126080.000000,1.447840e+03,1741.000000

In [26]:
df.isnull().sum()

id                             0
symbol                         0
name                           0
current_price                  0
market_cap                     0
market_cap_rank                0
total_volume                   0
high_24h                       0
low_24h                        0
price_change_24h               0
price_change_percentage_24h    0
circulating_supply             0
total_supply                   0
ath                            0
atl                            0
last_updated                   0
price_range_24h                0
market_cap_category            0
snapshot_date                  0
dtype: int64